cargo-features = ["strip"]

[workspace]
members = ["lambda_blue", "emulators/emulator_chip8"]
# default-members = ["lambda_blue"]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = 3
strip = true  # Automatically strip symbols from the binary.
